import { useState, type FormEvent } from 'react';
import { Plus, Pencil, RefreshCw, ArrowDownLeft, ArrowUpRight, Coins, Check, TrendingUp, RotateCcw, Search } from 'lucide-react';
import { Dialog, parseMoney, yuan, type Request } from './inventory.js';
import type { Account } from './accounts.js';
import './funds.css';
import { FundSnapshots, type SnapshotPool } from './fund-snapshots.js';
type Trade = { id: number; kind: string; shares: number; amount: number; fee: number; date: string; cancelled_at: string | null; note: string };
export type Fund = { id: number; account_id: number; code: string; name: string; platform: string; opening_shares: number; opening_cost: number; opening_date: string; benchmark: string; note: string;
  shares: number; cost: number; value: number | null; profit: number | null; profitRate: number | null; totalProfit: number | null; realized: number; dividends: number; unitCost: number | null;
  quote: { date: string; nav: number; source: string; fetched_at: string } | null; dailyProfit: number | null; navChange: number | null;
  reference: { name: string; quoted_at: string; source: string } | null; referenceFresh: boolean; referenceChange: number | null; referenceProfit: number | null;
  error: string; referenceError: string; trades: Trade[]; history: { date: string; nav: number }[] };
export type FundPool = { funds: Fund[]; value: number; cost: number; profit: number; unknown: number; reminder: { enabled: boolean; time: string }; lastRefresh: string; snapshots: SnapshotPool };
const signed = (n: number | null, percent = false) => n === null ? '待更新' : (n > 0 ? '+' : '') + (percent ? n.toFixed(2) + '%' : '¥' + yuan(n));
const tone = (n: number | null) => n === null ? '' : n > 0 ? 'fund-up' : n < 0 ? 'fund-down' : '';
const sharesText = (n: number) => (n / 10000).toFixed(4);
const kinds: Record<string, string> = { buy: '确认申购', sell: '确认赎回', dividend: '现金分红' };
const references = [['', '不关联'], ['sh512400', '有色金属 ETF · 512400'], ['sh518880', '黄金 ETF · 518880'], ['sh510300', '沪深300 ETF · 510300'], ['sh510500', '中证500 ETF · 510500'], ['sz159915', '创业板 ETF · 159915']];
export function FundsView({ pool, accounts, today, request, saved }: { pool: FundPool; accounts: Account[]; today: string; request: Request; saved: () => void }) {
  const [selected, setSelected] = useState<number | null>(null), [edit, setEdit] = useState<Fund | 'new' | null>(null), [trade, setTrade] = useState<Fund | null>(null), [nav, setNav] = useState<Fund | null>(null);
  const [cancel, setCancel] = useState<Trade | null>(null), [query, setQuery] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const detail = pool.funds.find(p => p.id === selected), funds = pool.funds.filter(p => [p.name, p.code, p.platform].some(v => v.includes(query)));
  const snapshotOnly = !pool.funds.length && pool.snapshots.snapshots.some(s => !s.position_id);
  async function refresh() { setBusy(true); setError(''); try { await request('/funds/refresh', {}); saved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="fund-view">
    {snapshotOnly ? <div className="metrics"><div><span>截图持仓金额 <TrendingUp size={16}/></span><strong>¥{yuan(pool.snapshots.value)}</strong><small>原始截图金额</small></div><div><span>截图持有收益 <ArrowUpRight size={16}/></span><strong className={tone(pool.snapshots.profit)}>{signed(pool.snapshots.profit)}</strong><small>份额与日期待补全</small></div><div><span>申购中 <Coins size={16}/></span><strong>¥{yuan(pool.snapshots.pending)}</strong><small>单列，未确认份额</small></div></div> : <div className="metrics"><div><span>最新净值市值 <TrendingUp size={16}/></span><strong>¥{yuan(pool.value)}</strong><small>{pool.unknown ? `${pool.unknown} 笔净值未知，未计入合计` : '已确认份额，不重复计资产'}</small></div><div><span>剩余持仓成本 <Coins size={16}/></span><strong>¥{yuan(pool.cost)}</strong><small>已确认份额 · 包含申购费用</small></div><div><span>持有收益 <ArrowUpRight size={16}/></span><strong className={tone(pool.profit)}>{signed(pool.profit)}</strong><small>按各基金最新公布净值 · {pool.unknown ? '仅含可估值持仓' : '未实现收益'}</small></div></div>}
    <div className="account-toolbar"><div className="search-input"><Search size={16}/><input aria-label="搜索基金" placeholder="名称、代码、平台" value={query} onChange={e => setQuery(e.target.value)}/></div><div className="fund-toolbar-actions"><button className="icon-button" title="更新净值与参考行情" aria-label="更新净值与参考行情" disabled={busy} onClick={() => { void refresh(); }}><RefreshCw size={17} className={busy ? 'spin' : ''}/></button><button className="button primary" onClick={() => setEdit('new')}><Plus size={16}/>添加持仓</button></div></div>
    <div className="fund-reminder"><label className="checkbox-label"><input type="checkbox" checked={pool.reminder.enabled} onChange={async e => { try { await request('/funds/reminder', { enabled: e.target.checked }, 'PUT'); saved(); } catch (e) { setError((e as Error).message); } }}/>交易日 14:50 基金提醒</label><small>{pool.lastRefresh ? '最近查询 ' + new Date(pool.lastRefresh).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '尚未查询行情'}</small></div>
    {error && <p className="error">{error}</p>}
    <FundSnapshots pool={pool.snapshots} accounts={accounts} request={request} today={today} saved={saved} query={query}/>
    {!snapshotOnly && <div className="table-wrap"><table className="fund-table"><thead><tr><th>基金 / 平台</th><th>市值 / 成本</th><th>持有收益</th><th>最新净值 / 日期</th><th>ETF参考涨跌</th><th aria-label="操作"/></tr></thead><tbody>{funds.map(p => <tr key={p.id} className={selected === p.id ? 'fund-selected' : ''}><td><button className="fund-name" onClick={() => setSelected(p.id)}><strong>{p.name}</strong><small>{p.code} · {p.platform || '未指定平台'} · {sharesText(p.shares)}份</small></button></td><td><strong>{p.value === null ? '待更新' : '¥' + yuan(p.value)}</strong><small className="type-label">成本 ¥{yuan(p.cost)}</small></td><td><strong className={tone(p.profit)}>{signed(p.profit)}</strong><small className={'type-label ' + tone(p.profitRate)}>{signed(p.profitRate, true)}</small></td><td><strong>{p.quote ? (p.quote.nav / 1000000).toFixed(4) : '待更新'}</strong><small className="type-label">{p.quote?.date || '日期未知'}{p.error ? ' · 更新失败' : ''}</small></td><td>{p.benchmark ? <><strong className={tone(p.referenceChange)}>{signed(p.referenceChange, true)}</strong><small className="type-label">{p.reference?.name || p.benchmark}{p.reference && !p.referenceFresh ? ' · 非实时' : ''}</small></> : <span className="muted">未关联</span>}</td><td><div className="row-actions"><button className="icon-button" title={'编辑 ' + p.name} aria-label={'编辑 ' + p.name} onClick={() => setEdit(p)}><Pencil size={15}/></button><button className="icon-button" title={'记录交易 ' + p.name} aria-label={'记录交易 ' + p.name} onClick={() => { setSelected(p.id); setTrade(p); }}><ArrowLeftRightIcon/></button></div></td></tr>)}</tbody></table>{!funds.length && <div className="empty"><TrendingUp size={32}/><p>{query ? '未找到已确认份额持仓' : '暂无已确认份额持仓'}</p>{!query && <button className="button" onClick={() => setEdit('new')}><Plus size={16}/>添加持仓</button>}</div>}</div>}
    {detail && <section className="fund-detail"><div className="section-heading"><div><h2>{detail.name}</h2><p className="muted">{detail.code} · {detail.quote?.source || '净值待更新'}</p></div><div className="fund-toolbar-actions"><button className="button" onClick={() => setNav(detail)}><Pencil size={15}/>录入净值</button><button className="button" onClick={() => setTrade(detail)}><Plus size={15}/>记录交易</button></div></div>
      <div className="fund-detail-grid"><div><dl><dt>持仓份额</dt><dd>{sharesText(detail.shares)}</dd><dt>单位成本</dt><dd>{detail.unitCost === null ? '无持仓' : '¥' + (detail.unitCost / 1000000).toFixed(4)}</dd><dt>累计收益</dt><dd className={tone(detail.totalProfit)}>{signed(detail.totalProfit)}</dd><dt>已实现收益</dt><dd className={tone(detail.realized)}>{signed(detail.realized)}</dd><dt>已收现金分红</dt><dd>¥{yuan(detail.dividends)}</dd><dt>{detail.quote?.date || '最新'} 净值变动收益</dt><dd className={tone(detail.dailyProfit)}>{detail.dailyProfit === null ? '记录不足' : signed(detail.dailyProfit)}</dd></dl>{detail.error && <p className="error">{detail.error}</p>}{detail.note && <p className="item-note">{detail.note}</p>}</div><NavChart history={detail.history}/></div>
      {detail.benchmark && <div className="fund-reference"><strong>ETF参考 · {detail.reference?.name || detail.benchmark}</strong><span className={tone(detail.referenceChange)}>{signed(detail.referenceChange, true)}</span><span>{detail.referenceProfit === null ? '参考金额待更新或当日有交易' : '参考变动 ' + signed(detail.referenceProfit)}</span><small>{detail.reference ? new Date(detail.reference.quoted_at).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '暂无行情'}{detail.reference && !detail.referenceFresh ? ' · 已过时' : ''}</small>{detail.referenceError && <small className="error">{detail.referenceError}</small>}</div>}
      <p className="muted fund-data-note">ETF涨跌是参考，不是基金盘中估值。累计收益包含已记录的赎回收益和现金分红。</p>
      <div className="table-wrap"><table><thead><tr><th>净值归属日</th><th>交易</th><th>份额</th><th>实际金额</th><th>费用</th><th aria-label="操作"/></tr></thead><tbody>{detail.trades.map(t => <tr key={t.id} className={t.cancelled_at ? 'cancelled' : ''}><td>{t.date}</td><td>{kinds[t.kind]}<small className="type-label">{t.cancelled_at ? '已撤销' : t.note}</small></td><td>{t.kind === 'dividend' ? '不变' : sharesText(t.shares)}</td><td>¥{yuan(t.amount)}</td><td>¥{yuan(t.fee)}</td><td>{!t.cancelled_at && <button className="icon-button" title="撤销基金交易" aria-label="撤销基金交易" onClick={() => setCancel(t)}><RotateCcw size={15}/></button>}</td></tr>)}</tbody></table>{!detail.trades.length && <p className="quiet-empty">暂无持仓变动</p>}</div>
    </section>}
    {edit && <FundForm fund={edit === 'new' ? undefined : edit} pool={pool} accounts={accounts} today={today} request={request} close={() => setEdit(null)} saved={saved}/>}
    {trade && <TradeForm fund={trade} accounts={accounts} today={today} request={request} close={() => setTrade(null)} saved={saved}/>}
    {nav && <NavForm fund={nav} today={today} request={request} close={() => setNav(null)} saved={saved}/>}
    {cancel && detail && <Dialog title="撤销基金交易" close={() => setCancel(null)}><p>撤销 {cancel.date} 的{kinds[cancel.kind]} ¥{yuan(cancel.amount)}，同时恢复关联现金变动。</p><footer><button className="button" onClick={() => setCancel(null)}>取消</button><button className="button danger" disabled={busy} onClick={async () => { setBusy(true); try { await request(`/funds/${detail.id}/trades/${cancel.id}/cancel`, {}); setCancel(null); saved(); } catch (e) { setError((e as Error).message); setCancel(null); } finally { setBusy(false); } }}><RotateCcw size={16}/>撤销</button></footer></Dialog>}
  </div>;
}
function ArrowLeftRightIcon() { return <Coins size={15}/>; }
function NavChart({ history }: { history: Fund['history'] }) {
  const rows = [...history].reverse(), min = Math.min(...rows.map(r => r.nav)), max = Math.max(...rows.map(r => r.nav)), spread = max - min || 1;
  return <div className="fund-chart"><h3>单位净值 · 最近{rows.length}期</h3>{rows.length ? <><svg role="img" aria-label="基金净值走势" viewBox="0 0 600 180" preserveAspectRatio="none"><line x1="10" y1="165" x2="590" y2="165" stroke="#dfe8e1"/><polyline fill="none" stroke="#167c69" strokeWidth="2" vectorEffect="non-scaling-stroke" points={rows.map((r, i) => `${10 + i / Math.max(1, rows.length - 1) * 580},${155 - (r.nav - min) / spread * 140}`).join(' ')}/>{rows.map((r, i) => <circle key={r.date} cx={10 + i / Math.max(1, rows.length - 1) * 580} cy={155 - (r.nav - min) / spread * 140} r={rows.length === 1 ? 3 : 2} fill="#167c69"><title>{r.date} · {(r.nav / 1000000).toFixed(4)}</title></circle>)}</svg><div className="fund-chart-labels"><span>{rows[0].date}</span><span>{(min / 1000000).toFixed(4)} ~ {(max / 1000000).toFixed(4)}</span><span>{rows.at(-1)!.date}</span></div></> : <div className="chart-empty">净值待更新</div>}</div>;
}
function FundForm({ fund, pool, accounts, today, request, saved, close }: { fund?: Fund; pool: FundPool; accounts: Account[]; today: string; request: Request; saved: () => void; close: () => void }) {
  const [f, setF] = useState({ code: fund?.code || '', name: fund?.name || '', platform: fund?.platform || '', shares: fund ? sharesText(fund.opening_shares) : '', cost: fund ? (fund.opening_cost / 100).toFixed(2) : '', date: fund?.opening_date || today, account_id: fund?.account_id.toString() || '', benchmark: fund?.benchmark || '', note: fund?.note || '' });
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const set = (k: string, v: string) => setF(p => ({ ...p, [k]: v }));
  const locked = !!fund?.trades.some(t => !t.cancelled_at);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { const cost = parseMoney(f.cost); if (cost === null) throw new Error('请填写剩余持仓成本'); await request(fund ? '/funds/' + fund.id : '/funds', { ...f, cost, ...(f.account_id ? { account_id: Number(f.account_id) } : { account_id: undefined }) }, fund ? 'PUT' : 'POST'); saved(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog title={fund ? '编辑基金持仓' : '添加已有基金持仓'} close={close}><form onSubmit={submit}><div className="form-grid">
    <label>基金代码<input aria-label="基金代码" required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" disabled={locked} value={f.code} onChange={e => set('code', e.target.value)}/></label>
    <label>基金名称<input aria-label="基金名称" required maxLength={100} value={f.name} onChange={e => set('name', e.target.value)}/></label>
    <label>持有平台<input aria-label="持有平台" maxLength={60} value={f.platform} disabled={!!fund || !!f.account_id} onChange={e => set('platform', e.target.value)}/></label>
    <label>关联资金账户<select aria-label="关联资金账户" disabled={!!fund} value={f.account_id} onChange={e => { set('account_id', e.target.value); if (e.target.value) set('platform', accounts.find(a => a.id === Number(e.target.value))!.platform); }}><option value="">新建独立投资账户</option>{accounts.filter(a => a.kind === 'investment' && (a.id === fund?.account_id || !pool.funds.some(p => p.account_id === a.id))).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
    <label>期初已确认份额<input aria-label="已确认份额" required disabled={locked} inputMode="decimal" value={f.shares} onChange={e => set('shares', e.target.value)}/></label>
    <label>期初剩余持仓成本（元）<input aria-label="持仓成本" required disabled={locked} inputMode="decimal" value={f.cost} onChange={e => set('cost', e.target.value)}/></label>
    <label>期初持仓日期<input aria-label="期初持仓日期" required type="date" max={today} disabled={locked} value={f.date} onInput={e => set('date', e.currentTarget.value)}/></label>
    <label>盘中参考 ETF<select aria-label="盘中参考ETF" value={references.some(([v]) => v === f.benchmark) ? f.benchmark : 'custom'} onChange={e => set('benchmark', e.target.value === 'custom' ? 'sh' : e.target.value)}>{references.map(([v, label]) => <option key={v} value={v}>{label}</option>)}<option value="custom">其他 ETF</option></select></label>
    {f.benchmark && !references.some(([v]) => v === f.benchmark) && <label>ETF行情代码<input aria-label="ETF行情代码" placeholder="sh512400" required value={f.benchmark} onChange={e => set('benchmark', e.target.value)}/></label>}
    </div>{f.account_id && !fund && <p className="muted">关联后，该账户市值按基金份额与最新净值计算，替代原手填余额。</p>}<label>备注<textarea maxLength={1000} value={f.note} onChange={e => set('note', e.target.value)}/></label>{error && <p className="error">{error}</p>}<footer><button className="button" type="button" onClick={close}>取消</button><button className="button primary" disabled={busy}><Check size={16}/>保存持仓</button></footer></form></Dialog>;
}
function TradeForm({ fund, accounts, today, request, saved, close }: { fund: Fund; accounts: Account[]; today: string; request: Request; saved: () => void; close: () => void }) {
  const [f, setF] = useState({ kind: 'buy', shares: '', amount: '', fee: '0', date: today, cash_account_id: '', note: '' }), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const set = (k: string, v: string) => setF(p => ({ ...p, [k]: v }));
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { const amount = parseMoney(f.amount); if (!amount) throw new Error('请填写实际金额'); await request('/funds/' + fund.id + '/trades', { ...f, shares: f.kind === 'dividend' ? '0' : f.shares, amount, fee: f.kind === 'dividend' ? 0 : parseMoney(f.fee) || 0, cash_account_id: f.cash_account_id ? Number(f.cash_account_id) : null }); saved(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog title={fund.name + ' · 记录已确认交易'} close={close}><form onSubmit={submit}><div className="segments">{Object.entries(kinds).map(([v, label]) => <button key={v} type="button" className={f.kind === v ? 'selected' : ''} onClick={() => set('kind', v)}>{label}</button>)}</div><div className="form-grid">{f.kind !== 'dividend' && <label>平台确认份额<input aria-label="交易确认份额" required inputMode="decimal" value={f.shares} onChange={e => set('shares', e.target.value)}/></label>}<label>{f.kind === 'buy' ? '总扣款（含费用，元）' : '实际到账（元）'}<input aria-label="交易实际金额" required inputMode="decimal" value={f.amount} onChange={e => set('amount', e.target.value)}/></label>{f.kind !== 'dividend' && <label>已包含的手续费（元）<input aria-label="基金手续费" inputMode="decimal" value={f.fee} onChange={e => set('fee', e.target.value)}/></label>}<label>{f.kind === 'dividend' ? '分红除息日' : '交易净值归属日'}<input aria-label="交易净值归属日" required type="date" min={fund.opening_date} max={today} value={f.date} onInput={e => set('date', e.currentTarget.value)}/></label><label>{f.kind === 'buy' ? '扣款账户' : '到账账户'}<select aria-label="交易现金账户" value={f.cash_account_id} onChange={e => set('cash_account_id', e.target.value)}><option value="">只更新持仓，不改现金余额</option>{accounts.filter(a => a.kind === 'cash').map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label>备注<textarea maxLength={1000} value={f.note} onChange={e => set('note', e.target.value)}/></label>{error && <p className="error">{error}</p>}<footer><button className="button" type="button" onClick={close}>取消</button><button className="button primary" disabled={busy}>{f.kind === 'buy' ? <ArrowUpRight size={16}/> : <ArrowDownLeft size={16}/>}保存交易</button></footer></form></Dialog>;
}
function NavForm({ fund, today, request, saved, close }: { fund: Fund; today: string; request: Request; saved: () => void; close: () => void }) {
  const [date, setDate] = useState(fund.quote?.date || today), [nav, setNav] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await request('/funds/' + fund.code + '/nav', { date, nav }); saved(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog title="录入正式净值" close={close}><form onSubmit={submit}><div className="form-grid"><label>净值日期<input type="date" aria-label="净值日期" required max={today} value={date} onInput={e => setDate(e.currentTarget.value)}/></label><label>单位净值<input inputMode="decimal" aria-label="单位净值" required value={nav} onChange={e => setNav(e.target.value)}/></label></div>{error && <p className="error">{error}</p>}<footer><button className="button" type="button" onClick={close}>取消</button><button className="button primary" disabled={busy}><Check size={16}/>保存净值</button></footer></form></Dialog>;
}
