import { useState } from 'react';
import { Plus,Pencil,X,Check,Archive,RotateCcw,Search,Package,Clock,Coins } from 'lucide-react';
import type { FormEvent,ReactNode } from 'react';
import './inventory.css';
export type Request=<T>(path:string,body?:unknown,method?:string)=>Promise<T>;
export const yuan=(n:number)=>(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
export function parseMoney(value:string) { if(!value)return null;if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('金额须为非负数，最多两位小数');const [w,p='']=value.split('.');return Number(w)*100+Number(p.padEnd(2,'0')); }
export function Dialog({title,close,children}:{title:string;close:()=>void;children:ReactNode}) {
  return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" title="关闭" aria-label="关闭" onClick={close}><X size={18}/></button></header>{children}</section></div>;
}
export type Item={id:number;name:string;category:string;price:number|null;purchased_on:string|null;retired_on:string|null;note:string;archived_at:string|null;usage_days:number|null;daily_cost:number|null};
export function PossessionsView({items,request,saved,archived,setArchived}:{items:Item[];request:Request;saved:()=>void;archived:boolean;setArchived:(v:boolean)=>void}) {
  const [edit,setEdit]=useState<Item|'new'|null>(null),[query,setQuery]=useState(''),[error,setError]=useState('');
  const active=items.filter(i=>!i.archived_at),known=active.filter(i=>i.price!==null),rows=items.filter(i=>i.name.includes(query)||i.category.includes(query));
  return <div className="inventory-view"><div className="metrics"><div><span>物品数量 <Package size={16}/></span><strong>{active.length}</strong><small>未归档物品</small></div><div><span>购入价合计 <Coins size={16}/></span><strong>¥{yuan(known.reduce((n,i)=>n+i.price!,0))}</strong><small>{active.length-known.length} 件价格待补全 · 不计入现金净资产</small></div><div><span>每日使用成本 <Clock size={16}/></span><strong>¥{yuan(active.reduce((n,i)=>n+(i.daily_cost??0),0))}</strong><small>购入价 ÷ 已用天数 · 当天购买按1天</small></div></div>
    <div className="account-toolbar"><div className="search-input"><Search size={16}/><input aria-label="搜索物品" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或分类"/></div><label className="checkbox-label"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>包含归档</label><button className="button primary" onClick={()=>setEdit('new')}><Plus size={16}/>新增物品</button></div>
    {error&&<p className="error">{error}</p>}
    <div className="table-wrap"><table><thead><tr><th>物品 / 分类</th><th>购入价</th><th>购买日</th><th>已用天数</th><th>平均每天</th><th aria-label="操作"/></tr></thead><tbody>{rows.map(i=><tr key={i.id} className={i.archived_at?'cancelled':''}><td><strong>{i.name}</strong><small className="type-label">{i.category}{i.retired_on?' · 已停用':''}{i.archived_at?' · 已归档':''}</small>{i.note&&<small className="item-note">{i.note}</small>}</td><td>{i.price===null?'待补全':'¥'+yuan(i.price)}</td><td>{i.purchased_on||'待补全'}</td><td>{i.usage_days===null?'待补全':i.usage_days+'天'}</td><td>{i.daily_cost===null?'待补全':'¥'+yuan(i.daily_cost)}</td><td><div className="row-actions"><button className="icon-button" title={'编辑 '+i.name} aria-label={'编辑 '+i.name} onClick={()=>setEdit(i)}><Pencil size={16}/></button><button className="icon-button" title={i.archived_at?'恢复物品':'归档物品'} aria-label={i.archived_at?'恢复物品':'归档物品'} onClick={async()=>{try{await request('/possessions/'+i.id+'/archive',{archived:!i.archived_at});saved();}catch(e){setError((e as Error).message);}}}>{i.archived_at?<RotateCcw size={16}/>:<Archive size={16}/>}</button></div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty"><Package size={32}/><p>暂无物品记录</p></div>}</div>
    {edit&&<ItemForm item={edit==='new'?undefined:edit} request={request} close={()=>setEdit(null)} saved={saved}/>}
  </div>;
}
function ItemForm({item,request,close,saved}:{item?:Item;request:Request;close:()=>void;saved:()=>void}) {
  const [form,setForm]=useState({name:item?.name||'',category:item?.category||'数码',price:item?.price==null?'':(item.price/100).toFixed(2),purchased_on:item?.purchased_on||'',retired_on:item?.retired_on||'',note:item?.note||''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const set=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await request(item?'/possessions/'+item.id:'/possessions',{...form,price:parseMoney(form.price),purchased_on:form.purchased_on||null,retired_on:form.retired_on||null},item?'PUT':'POST');saved();close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog title={item?'编辑物品':'新增物品'} close={close}><form onSubmit={submit}><div className="form-grid"><label>物品名称<input aria-label="物品名称" value={form.name} onChange={e=>set('name',e.target.value)} required maxLength={100}/></label><label>分类<select value={form.category} onChange={e=>set('category',e.target.value)}>{[...new Set(['数码','耳机','手表','家电','家具','其他',form.category])].map(c=><option key={c}>{c}</option>)}</select></label><label>购入价格（元）<input aria-label="购入价格" inputMode="decimal" value={form.price} placeholder="待补全" onChange={e=>set('price',e.target.value)}/></label><label>购买日期<input aria-label="物品购买日期" type="date" value={form.purchased_on} onInput={e=>set('purchased_on',e.currentTarget.value)}/></label><label>停用日期<input aria-label="物品停用日期" type="date" value={form.retired_on} onInput={e=>set('retired_on',e.currentTarget.value)}/></label></div><label>备注<textarea value={form.note} onChange={e=>set('note',e.target.value)} maxLength={1000}/></label>{error&&<p className="error">{error}</p>}<footer><button type="button" className="button" onClick={close}>取消</button><button className="button primary" disabled={busy}><Check size={16}/>保存物品</button></footer></form></Dialog>;
}
