import { useState } from 'react';
import { Plus,Pencil,Coins,CalendarDays,CreditCard,ArrowDownLeft,ArrowUpRight,ListPlus,Check } from 'lucide-react';
import { Dialog,parseMoney,yuan,type Request } from './inventory.js';
import type { Account } from './accounts.js';
import type { FormEvent } from 'react';
export type Installment={id:number;due_date:string;principal:number;interest:number;paid_principal:number;paid_interest:number;note:string};
export type Loan={account_id:number;name:string;balance:number|null;category:string;creditor:string;repayment_start:string|null;monthly_payment:number|null;due_day:number|null;maturity_date:string|null;annual_rate:string|null;subsidy_until:string|null;note:string;overdue:number;installments:Installment[];projected:{due_date:string;amount:number}[];events:{id:number;kind:string;date:string;amount:number;interest:number;note:string;principal_cancelled:number;interest_cancelled:number}[]};
export type LoanPool={loans:Loan[];total:number;unknown:number;this_month:number;overdue:number};
const categories={student:'助学贷款',monthly:'月付',personal:'亲友借款',other:'其他贷款'};
export function LoansView({pool,accounts,today,request,saved}:{pool:LoanPool;accounts:Account[];today:string;request:Request;saved:()=>void}) {
  const [filter,setFilter]=useState(''),[selected,setSelected]=useState<number|null>(null),[edit,setEdit]=useState<Loan|'new'|null>(null),[action,setAction]=useState<{loan:Loan;type:'repay'|'draw'|'installment';installment?:Installment}|null>(null);
  const loans=pool.loans.filter(l=>!filter||l.category===filter),detail=pool.loans.find(l=>l.account_id===selected);
  return <div className="loans-view"><div className="metrics"><div><span>尚欠金额 <CreditCard size={16}/></span><strong className="debt">¥{yuan(pool.total)}</strong><small>{pool.unknown} 笔金额待补全 · 与资金账户同步</small></div><div><span>本月分期待还 <CalendarDays size={16}/></span><strong>¥{yuan(pool.this_month)}</strong><small>已录入合同分期 · 含本金与利息</small></div><div><span>逾期计划未还 <Coins size={16}/></span><strong>¥{yuan(pool.overdue)}</strong><small>按已录入分期和关联还款计算</small></div></div>
    <div className="account-toolbar"><div className="account-tabs" role="tablist" aria-label="借款类型">{[['','全部'],...Object.entries(categories)].map(([id,label])=><button key={id} role="tab" aria-selected={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><button className="button primary" onClick={()=>setEdit('new')}><Plus size={16}/>新增借款</button></div>
    <div className="loan-layout"><div className="loan-list">{loans.map(l=><section className={'loan-row'+(selected===l.account_id?' selected':'')} key={l.account_id}><button className="loan-select" onClick={()=>setSelected(l.account_id)}><span><strong>{l.name}</strong><small>{categories[l.category as keyof typeof categories]} · {l.creditor||'债权人待补全'}</small></span><strong>{l.balance===null?'待补全':'¥'+yuan(l.balance)}</strong></button><div className="loan-meta"><span>开始还款 {l.repayment_start||'待补全'}</span><span>{l.monthly_payment===null?'月还金额待补全':'月还 ¥'+yuan(l.monthly_payment)}{l.due_day?' · 每月'+l.due_day+'日':''}</span></div><div className="loan-actions"><button className="icon-button" title={'编辑 '+l.name} aria-label={'编辑 '+l.name} onClick={()=>setEdit(l)}><Pencil size={16}/></button><button className="button" onClick={()=>setAction({loan:l,type:'draw'})}><ArrowDownLeft size={15}/>新增本金</button><button className="button" onClick={()=>setAction({loan:l,type:'repay'})}><ArrowUpRight size={15}/>记录还款</button></div></section>)}{!loans.length&&<p className="quiet-empty">暂无这类借款</p>}</div>
    <section className="loan-detail">{detail?<><div className="section-heading"><h2>{detail.name}</h2><button className="icon-button" title="新增分期计划" aria-label="新增分期计划" onClick={()=>setAction({loan:detail,type:'installment'})}><ListPlus size={18}/></button></div><dl><dt>合同到期</dt><dd>{detail.maturity_date||'待补全'}</dd><dt>年利率</dt><dd>{detail.annual_rate===null?'待补全':detail.annual_rate+'%'}</dd><dt>贴息截止</dt><dd>{detail.subsidy_until||'待补全'}</dd></dl>{detail.note&&<p className="item-note">{detail.note}</p>}<h3>合同分期</h3>{detail.installments.length?<div className="installment-list">{detail.installments.map(i=>{const remaining=i.principal+i.interest-i.paid_principal-i.paid_interest;return <div key={i.id}><span><strong>{i.due_date}</strong><small>本金 ¥{yuan(i.principal)} · 利息 ¥{yuan(i.interest)}</small><small>{remaining===0?'已还清':i.due_date<today?'计划已逾期':'待还'} ¥{yuan(remaining)}</small></span><div className="row-actions"><button className="icon-button" title="编辑分期" aria-label="编辑分期" onClick={()=>setAction({loan:detail,type:'installment',installment:i})}><Pencil size={16}/></button><button className="icon-button" title="还该分期" aria-label="还该分期" disabled={remaining===0} onClick={()=>setAction({loan:detail,type:'repay',installment:i})}><ArrowUpRight size={16}/></button></div></div>;})}</div>:<p className="quiet-empty">分期计划待补全</p>}<h3>未来月付预览</h3>{detail.projected.length?<><p className="muted">按固定月还金额预览，不代表银行账单或本金摊还计划。</p>{detail.projected.map(p=><div className="health-row" key={p.due_date}><span>{p.due_date}</span><b>¥{yuan(p.amount)}</b></div>)}</>:<p className="quiet-empty">起始日、月还金额或还款日待补全</p>}</>:<p className="quiet-empty">未选择借款</p>}</section></div>
    {detail&&<section className="loan-history"><h2>{detail.name} · 借还记录</h2><div className="table-wrap"><table><thead><tr><th>日期</th><th>类型</th><th>本金</th><th>利息</th><th>状态 / 备注</th></tr></thead><tbody>{detail.events?.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.kind==='draw'?'新增本金':'还款'}</td><td>¥{yuan(e.amount)}</td><td>¥{yuan(e.interest)}</td><td>{e.principal_cancelled?'本金已撤销':e.interest_cancelled?'利息已撤销':'已记录'}{e.note?' · '+e.note:''}</td></tr>)}</tbody></table>{!detail.events?.length&&<p className="quiet-empty">暂无借还记录</p>}</div></section>}
    {edit&&<LoanForm loan={edit==='new'?undefined:edit} close={()=>setEdit(null)} request={request} saved={saved}/>}
    {action&&<LoanAction {...action} accounts={accounts} today={today} close={()=>setAction(null)} request={request} saved={saved}/>}
  </div>;
}
function LoanForm({loan,close,request,saved}:{loan?:Loan;close:()=>void;request:Request;saved:()=>void}) {
  const [f,setF]=useState({name:loan?.name||'',balance:loan?.balance==null?'':(loan.balance/100).toFixed(2),category:loan?.category||'student',creditor:loan?.creditor||'',repayment_start:loan?.repayment_start||'',monthly_payment:loan?.monthly_payment==null?'':(loan.monthly_payment/100).toFixed(2),due_day:loan?.due_day?.toString()||'',maturity_date:loan?.maturity_date||'',annual_rate:loan?.annual_rate||'',subsidy_until:loan?.subsidy_until||'',note:loan?.note||''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const set=(key:string,value:string)=>setF(v=>({...v,[key]:value}));
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await request(loan?'/loans/'+loan.account_id:'/loans',{...f,balance:parseMoney(f.balance),monthly_payment:parseMoney(f.monthly_payment),due_day:f.due_day?Number(f.due_day):null,repayment_start:f.repayment_start||null,maturity_date:f.maturity_date||null,subsidy_until:f.subsidy_until||null,annual_rate:f.annual_rate||null},loan?'PUT':'POST');saved();close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog title={loan?'编辑借款':'新增借款'} close={close}><form onSubmit={submit}><div className="form-grid"><label>借款名称<input aria-label="借款名称" required maxLength={100} value={f.name} onChange={e=>set('name',e.target.value)}/></label><label>借款类型<select aria-label="借款类型" value={f.category} onChange={e=>set('category',e.target.value)}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>尚欠本金（元）<input aria-label="尚欠本金" inputMode="decimal" value={f.balance} onChange={e=>set('balance',e.target.value)} placeholder="待补全"/></label><label>债权人<input aria-label="债权人" value={f.creditor} onChange={e=>set('creditor',e.target.value)} maxLength={100}/></label><label>开始还款日期<input aria-label="开始还款日期" type="date" value={f.repayment_start} onInput={e=>set('repayment_start',e.currentTarget.value)}/></label><label>月还金额（元）<input aria-label="月还金额" inputMode="decimal" value={f.monthly_payment} onChange={e=>set('monthly_payment',e.target.value)} placeholder="待补全"/></label><label>每月还款日<input aria-label="每月还款日" type="number" min={1} max={31} value={f.due_day} onChange={e=>set('due_day',e.target.value)}/></label><label>合同到期日期<input aria-label="合同到期日期" type="date" value={f.maturity_date} onInput={e=>set('maturity_date',e.currentTarget.value)}/></label><label>年利率（%）<input aria-label="年利率" inputMode="decimal" value={f.annual_rate} onChange={e=>set('annual_rate',e.target.value)} placeholder="待补全"/></label><label>贴息截止日期<input aria-label="贴息截止日期" type="date" value={f.subsidy_until} onInput={e=>set('subsidy_until',e.currentTarget.value)}/></label></div><label>备注<textarea value={f.note} onChange={e=>set('note',e.target.value)} maxLength={1000}/></label>{error&&<p className="error">{error}</p>}<footer><button className="button" type="button" onClick={close}>取消</button><button className="button primary" disabled={busy}><CheckIcon/>保存借款</button></footer></form></Dialog>;
}
function CheckIcon(){return <Check size={16}/>;}
function LoanAction({loan,type,installment,accounts,today,close,request,saved}:{loan:Loan;type:'repay'|'draw'|'installment';installment?:Installment;accounts:Account[];today:string;close:()=>void;request:Request;saved:()=>void}) {
  const [f,setF]=useState({amount:installment?((installment.principal-(type==='repay'?installment.paid_principal:0))/100).toFixed(2):'',interest:installment?((installment.interest-(type==='repay'?installment.paid_interest:0))/100).toFixed(2):'0',date:type==='installment'&&installment?installment.due_date:today,cash_account_id:'',note:type==='installment'?installment?.note||'':''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const set=(key:string,value:string)=>setF(v=>({...v,[key]:value}));
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const amount=parseMoney(f.amount);if(amount===null)throw new Error('请填写金额');await request('/loans/'+loan.account_id+'/'+(type==='installment'?'installments'+(installment?'/'+installment.id:''):type),type==='installment'?{due_date:f.date,principal:amount,interest:parseMoney(f.interest)||0,note:f.note}:{amount,interest:parseMoney(f.interest)||0,date:f.date,...(f.cash_account_id?{cash_account_id:Number(f.cash_account_id)}:{}),...(installment?{installment_id:installment.id}:{}),note:f.note},type==='installment'&&installment?'PUT':'POST');saved();close();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog title={loan.name+' · '+({repay:'记录还款',draw:'新增本金',installment:'新增分期'})[type]} close={close}><form onSubmit={submit}><div className="form-grid"><label>{type==='draw'?'新增本金（元）':'本金（元）'}<input aria-label="操作本金" required inputMode="decimal" value={f.amount} onChange={e=>set('amount',e.target.value)}/></label>{type!=='draw'&&<label>利息（元）<input aria-label="操作利息" inputMode="decimal" value={f.interest} onChange={e=>set('interest',e.target.value)}/></label>}<label>{type==='installment'?'应还日期':'发生日期'}<input aria-label="操作日期" type="date" required value={f.date} onInput={e=>set('date',e.currentTarget.value)}/></label>{type!=='installment'&&<label>{type==='repay'?'付款账户':'到账账户'}<select aria-label="操作资金账户" value={f.cash_account_id} required={type==='repay'} onChange={e=>set('cash_account_id',e.target.value)}><option value="">{type==='repay'?'请选择':'仅累计本金'}</option>{accounts.filter(a=>a.kind==='cash').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}</div><label>备注<textarea value={f.note} maxLength={1000} onChange={e=>set('note',e.target.value)}/></label>{error&&<p className="error">{error}</p>}<footer><button className="button" type="button" onClick={close}>取消</button><button className="button primary" disabled={busy}><Coins size={16}/>保存</button></footer></form></Dialog>;
}
