import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownLeft, ArrowUpRight, ArrowLeftRight, RotateCcw, Plus, Search, Download, Pencil, Trash2, X, Check, Send, RefreshCw, Wallet, LayoutDashboard, List, FileText, Settings, Activity, ChevronRight, LoaderCircle, CircleCheck, CircleAlert, Database, Link, CalendarDays, ReceiptText, Package, CreditCard, ImagePlus } from 'lucide-react';
import './style.css';
import { AccountsView, type Account, type Funds } from './accounts.js';
import { ReminderSettings } from './reminder-settings.js';
import { ModelSettings } from './model-settings.js';
import { PossessionsView,type Item } from './inventory.js';
import { LoansView,type LoanPool } from './loans.js';
import { ChartControls } from './chart-controls.js';
type Entry = { id: number; kind: string; amount: number; date: string; category: string; subcategory: string; merchant: string; note: string; parent_id: number | null; account_id: number | null; to_account_id: number | null; refunded_amount: number; cancelled_at: string | null; source: string };
type Summary = { income: number; expense: number; refunds: number; netExpense: number; balance: number; count: number; unclassified: number; categories: { name: string; amount: number }[]; days: { date: string; income: number; expense: number }[] };
type Status = { bot: { state: string; lastError: string | null; lastReceived: string | null; lastSent: string | null }; owner: string; pendingUser: string; pendingMessages: { id: string; text: string; status: string; error: string; received_at: string }[]; confirmations: { id: number; action: { type: string; amount?: string }; candidates: Entry[] }[]; outbox: number; lastBackup: string; dataDir: string; reminder: { enabled: boolean; time: string }; model: string; reasoning: string; baseUrl: string; aiConfigured: boolean; feishuConfigured: boolean; appId: string };
type Report = { id: number; period: string; start: string; end: string; cutoff: string; text: string; created_at: string };
let token = '';
async function api<T>(path: string, body?: unknown, method = body === undefined ? 'GET' : 'POST'): Promise<T> {
  const r = await fetch('/api' + path, { method, headers: { ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}), 'X-Ledger-Token': token }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
  const data = await r.json(); if (!r.ok) throw new Error(data.error || '请求失败'); return data;
}
const yuan = (n: number) => (n / 100).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const names: Record<string, string> = { expense: '支出', income: '收入', refund: '退款', transfer: '转账' };
const icons: Record<string, typeof Wallet> = { expense: ArrowUpRight, income: ArrowDownLeft, refund: RotateCcw, transfer: ArrowLeftRight };
const colors = ['#167c69', '#e49a3b', '#569ac6', '#d86875', '#8973ad', '#849c47'];
const categories = ['餐饮', '交通', '购物', '居住', '生活', '娱乐', '健康', '学习', '工资', '红包', '其他', '待分类'];
function historyText(raw: string) {
  const e = JSON.parse(raw) as Entry;
  return `${e.date} · ${names[e.kind]} ¥${yuan(e.amount)}\n${e.category}${e.subcategory ? ' / ' + e.subcategory : ''}\n${[e.merchant, e.note].filter(Boolean).join(' · ')}${e.parent_id ? '\n关联支出 #' + e.parent_id : ''}`;
}
function IconButton({ title, onClick, children, disabled, danger }: { title: string; onClick: () => void; children: React.ReactNode; disabled?: boolean; danger?: boolean }) {
  return <button className={'icon-button' + (danger ? ' danger' : '')} type="button" title={title} aria-label={title} onClick={onClick} disabled={disabled}>{children}</button>;
}
function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) {
  useEffect(() => { const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') close(); }; document.addEventListener('keydown', handler); return () => document.removeEventListener('keydown', handler); }, [close]);
  return <div className="overlay" onClick={e => { if (e.target === e.currentTarget) close(); }}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><IconButton title="关闭" onClick={close}><X size={19}/></IconButton></header>{children}</section></div>;
}
function EntryForm({ entry, refund, today, accounts, close, saved }: { entry?: Entry; refund?: Entry; today: string; accounts: Account[]; close: () => void; saved: () => void }) {
  const [form, setForm] = useState({ kind: refund ? 'refund' : entry?.kind || 'expense', amount: entry ? (entry.amount / 100).toFixed(2) : refund ? ((refund.amount - refund.refunded_amount) / 100).toFixed(2) : '', date: entry?.date || today, category: refund?.category || entry?.category || '餐饮', subcategory: refund?.subcategory || entry?.subcategory || '', merchant: refund?.merchant || entry?.merchant || '', note: entry?.note || (refund ? '退款到账' : ''), parent_id: refund?.id || entry?.parent_id || null, account_id: entry?.account_id || refund?.account_id || '', to_account_id: entry?.to_account_id || '' });
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const set = (key: string, value: string) => setForm(f => ({ ...f, [key]: value }));
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setError('');
    try {
      if (!/^\d+(\.\d{1,2})?$/.test(form.amount)) throw new Error('金额最多两位小数');
      const [whole, fraction = ''] = form.amount.split('.');
      if (form.kind === 'transfer' && (!form.account_id || !form.to_account_id)) throw new Error('请选择转出和转入账户');
      await api(entry ? '/entries/' + entry.id : '/entries', { ...form, account_id: form.account_id ? Number(form.account_id) : null, to_account_id: form.kind === 'transfer' && form.to_account_id ? Number(form.to_account_id) : null, amount: Number(whole) * 100 + Number(fraction.padEnd(2, '0')) }, entry ? 'PUT' : 'POST'); saved(); close();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Modal title={refund ? `退款 · 原支出 #${refund.id}` : entry ? `编辑记录 #${entry.id}` : '新增记录'} close={close}><form onSubmit={submit}>
    {!refund && !entry?.parent_id && <div className="segments">{['expense', 'income', 'transfer'].map(k => <button key={k} className={form.kind === k ? 'selected' : ''} type="button" onClick={() => set('kind', k)}>{names[k]}</button>)}</div>}
    <div className="amount-input"><span>¥</span><input aria-label="金额" placeholder="0.00" inputMode="decimal" value={form.amount} onChange={e => set('amount', e.target.value)} autoFocus required/></div>
    <div className="form-grid"><label>日期<input type="date" value={form.date} onInput={e => set('date', e.currentTarget.value)} required/></label><label>分类<select value={form.category} disabled={!!refund || !!entry?.parent_id} onChange={e => set('category', e.target.value)}>{[...new Set([...categories, form.category])].map(c => <option key={c}>{c}</option>)}</select></label><label>子分类<input value={form.subcategory} disabled={!!refund || !!entry?.parent_id} onChange={e => set('subcategory', e.target.value)} maxLength={30}/></label><label>商家<input value={form.merchant} onChange={e => set('merchant', e.target.value)} maxLength={100}/></label></div>
    <div className="form-grid"><label>{form.kind === 'transfer' ? '转出账户' : form.kind === 'expense' ? '付款账户' : '收款账户'}<select value={form.account_id} onChange={e => set('account_id', e.target.value)}><option value="">未指定</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{form.kind === 'transfer' && <label>转入账户<select value={form.to_account_id} onChange={e => set('to_account_id', e.target.value)}><option value="">请选择</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}</div>
    <label>备注<textarea value={form.note} onChange={e => set('note', e.target.value)} maxLength={1000}/></label>
    {form.parent_id && <p className="muted">关联支出 #{form.parent_id}</p>}{error && <p className="error">{error}</p>}
    <footer><button type="button" className="button" onClick={close}>取消</button><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16}/> : <Check size={16}/>}保存</button></footer>
  </form></Modal>;
}
function SettingsView({ status, refresh, toast }: { status: Status; refresh: () => void; toast: (s: string) => void }) {
  return <div className="settings-content"><ModelSettings value={status} request={api} saved={refresh} notify={toast}/>
    <section className="setting-section"><h2>飞书</h2><dl><dt>应用ID</dt><dd>{status.appId || '未配置'}</dd><dt>绑定用户</dt><dd className="wrap">{status.owner || '未绑定'}</dd><dt>连接</dt><dd>{stateName(status.bot.state)}</dd></dl>{!status.owner && status.pendingUser && <button className="button primary" onClick={async () => { try { await api('/bind', { user: status.pendingUser }); refresh(); toast('飞书用户已绑定'); } catch(e) { toast((e as Error).message); } }}><Link size={16}/>绑定待确认用户</button>}{status.appId && <a className="button" href={`https://open.feishu.cn/app/${status.appId}`} target="_blank" rel="noreferrer"><ArrowUpRight size={16}/>应用后台</a>}</section>
    <ReminderSettings value={status.reminder} save={async value => { const result = await api('/reminders', value, 'PUT'); refresh(); return result; }} notify={toast}/>
    <section className="setting-section"><h2>账单与存储</h2><dl><dt>时区 / 币种</dt><dd>北京时间 / 人民币</dd><dt>日报</dt><dd>每天 21:30</dd><dt>周报</dt><dd>周日 21:30</dd><dt>月报</dt><dd>每月1日 09:00</dd><dt>最近备份</dt><dd>{status.lastBackup || '暂无'}</dd><dt>数据目录</dt><dd className="wrap">{status.dataDir}</dd></dl><button className="button" onClick={async () => { try { await api('/backup', {}); refresh(); toast('账本已备份'); } catch(e) { toast((e as Error).message); } }}><Database size={16}/>立即备份</button></section></div>;
}
function stateName(state: string) { return ({ disabled: '未启用', connecting: '连接中', connected: '已连接', reconnecting: '重连中', error: '连接异常' } as Record<string, string>)[state] || state; }
function App() {
  const [view, setView] = useState('overview'), [date, setDate] = useState(''), [range, setRange] = useState({ start: '', end: '' });
  const [entries, setEntries] = useState<Entry[]>([]), [stats, setStats] = useState<Summary | null>(null), [status, setStatus] = useState<Status | null>(null), [reports, setReports] = useState<Report[]>([]);
  const [funds, setFunds] = useState<Funds | null>(null);
  const [items,setItems]=useState<Item[]>([]),[loans,setLoans]=useState<LoanPool|null>(null),[archived,setArchived]=useState(false),[chatImages,setChatImages]=useState<string[]>([]);
  const [kind, setKind] = useState(''), [category, setCategory] = useState(''), [query, setQuery] = useState(''), [cancelled, setCancelled] = useState(false);
  const [toast, setToast] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true), [form, setForm] = useState<{ entry?: Entry; refund?: Entry } | null>(null);
  const [text, setText] = useState(''), [reply, setReply] = useState(''), [sending, setSending] = useState(false), [reportText, setReportText] = useState(''), [deleting, setDeleting] = useState<Entry | null>(null), [history, setHistory] = useState<{ action: string; created_at: string; before_json: string | null; after_json: string | null }[] | null>(null);
  const notify = (s: string) => { setToast(s); window.setTimeout(() => setToast(''), 4500); };
  useEffect(() => { api<{ csrf: string; today: string }>('/bootstrap').then(data => { token = data.csrf; setDate(data.today); setRange({ start: data.today.slice(0, 7) + '-01', end: data.today }); }).catch(e => { setError(e.message); setLoading(false); }); }, []);
  async function refresh() {
    if (!range.start || !range.end) return;
    try {
      const params = new URLSearchParams({ ...range, ...(kind ? { kind } : {}), ...(category ? { category } : {}), ...(query ? { q: query } : {}), includeCancelled: String(cancelled) });
      const results = await Promise.all([api<Entry[]>('/entries?' + params), api<Summary>('/summary?' + new URLSearchParams(range)), api<Status>('/status'), api<Report[]>('/reports'), api<Funds>('/accounts'),api<Item[]>('/possessions?archived='+archived),api<LoanPool>('/loans')]);
      setEntries(results[0]); setStats(results[1]); setStatus(results[2]); setReports(results[3]); setFunds(results[4]);setItems(results[5]);setLoans(results[6]); setError('');
    } catch(e) { setError((e as Error).message); } finally { setLoading(false); }
  }
  useEffect(() => { void refresh(); const timer = setInterval(() => { void refresh(); }, 15000); return () => clearInterval(timer); }, [range.start, range.end, kind, category, query, cancelled,archived]);
  async function chat(e: React.FormEvent) { e.preventDefault(); if (!text.trim()) return; setSending(true); setReply('');setChatImages([]); try { const result = await api<{ result: string;images?:string[] }>('/chat', { text }); setReply(result.result);setChatImages(result.images||[]); setText(''); await refresh(); } catch(e) { setReply((e as Error).message); } finally { setSending(false); } }
  async function upload(file?:File){if(!file)return;setSending(true);setChatImages([]);try{if(file.size>8*1024*1024)throw new Error('图片不能超过8MB');const image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('图片读取失败'));reader.readAsDataURL(file);});setReply((await api<{result:string}>('/images',{image})).result);await refresh();}catch(e){setReply((e as Error).message);}finally{setSending(false);}}
  async function remove() { if (!deleting) return; try { await api('/entries/' + deleting.id, undefined, 'DELETE'); setDeleting(null); await refresh(); notify('记录已撤销'); } catch(e) { notify((e as Error).message); } }
  const nav = [{ id: 'overview', label: '总览', icon: LayoutDashboard }, { id: 'accounts', label: '资金账户', icon: Wallet }, {id:'possessions',label:'物品清单',icon:Package},{id:'loans',label:'贷款与借款',icon:CreditCard}, { id: 'entries', label: '账目明细', icon: List }, { id: 'reports', label: '账单', icon: FileText }, { id: 'activity', label: '运行状态', icon: Activity }, { id: 'settings', label: '设置', icon: Settings }];
  const issueCount = (status?.pendingMessages.length || 0) + (status?.confirmations.length || 0);
  const title = nav.find(n => n.id === view)?.label || '';
  const list = (rows: Entry[], compact = false) => <div className="table-wrap"><table><thead><tr><th>日期 / 记录</th><th>分类</th><th>金额</th><th>状态</th><th aria-label="操作"/></tr></thead><tbody>{rows.map(e => {
    const Icon = icons[e.kind] || Wallet;
    const account = funds?.accounts.find(a => a.id === e.account_id), target = funds?.accounts.find(a => a.id === e.to_account_id);
    return <tr key={e.id} className={e.cancelled_at ? 'cancelled' : ''}>
      <td><div className="entry-cell"><span className={'entry-icon ' + e.kind}><Icon size={17}/></span><div><strong>{e.merchant || e.note || e.category}</strong><span>{e.date} <i>#{e.id}</i>{e.merchant && e.note ? ' · ' + e.note : ''}</span>{account && <span>{account.name}{target ? ' → ' + target.name : ''}</span>}</div></div></td>
      <td><div className="category-cell">{e.category}<small>{e.subcategory || '—'}</small></div></td>
      <td><strong className={'money ' + e.kind}>{e.kind === 'expense' ? '−' : e.kind === 'transfer' ? '' : '+'}¥{yuan(e.amount)}</strong><small className="type-label">{names[e.kind]}</small></td>
      <td><span className={'status-label ' + (e.cancelled_at ? 'grey' : e.refunded_amount ? 'amber' : '')}>{e.cancelled_at ? '已撤销' : e.kind === 'refund' ? `关联 #${e.parent_id}` : e.refunded_amount ? e.refunded_amount === e.amount ? '已全额退款' : `已退 ¥${yuan(e.refunded_amount)}` : '已入账'}</span></td>
      <td><div className="row-actions">{!e.cancelled_at && <><IconButton title="编辑记录" onClick={() => setForm({ entry: e })}><Pencil size={15}/></IconButton>{e.kind === 'expense' && e.refunded_amount < e.amount && <IconButton title="记录退款" onClick={() => setForm({ refund: e })}><RotateCcw size={15}/></IconButton>}<IconButton title="撤销记录" onClick={() => setDeleting(e)} danger><Trash2 size={15}/></IconButton></>}<IconButton title="修改历史" onClick={async () => { try { setHistory(await api('/entries/' + e.id + '/history')); } catch(err) { notify((err as Error).message); } }}><ReceiptText size={15}/></IconButton></div></td>
    </tr>;
  })}</tbody></table>{rows.length === 0 && <div className="empty"><ReceiptText size={32} strokeWidth={1.3}/><p>{compact ? '本期暂无账目' : '暂无符合条件的记录'}</p><button className="button" onClick={() => setForm({})}><Plus size={16}/>新增记录</button></div>}</div>;
  return <div className="app"><aside className="sidebar"><div className="brand"><span><Wallet size={24}/></span><div>私人账本<small>PERSONAL LEDGER</small></div></div><nav>{nav.map(n => <button key={n.id} aria-label={n.label} title={n.label} className={view === n.id ? 'active' : ''} onClick={() => setView(n.id)}><n.icon size={18}/><span>{n.label}</span>{n.id === 'activity' && issueCount > 0 && <b>{issueCount}</b>}</button>)}</nav><div className="sidebar-bottom"><span className="avatar">我</span><div>个人账户<small>本机 · v0.3.1</small></div><span className="local-dot"/></div></aside>
    <main><header className="topbar"><span className="breadcrumb">个人账本 <ChevronRight size={14}/> {title}</span><button className="connection" onClick={() => setView('activity')}><span className={'dot ' + (status?.bot.state === 'connected' ? 'online' : '')}/><span>飞书{status ? stateName(status.bot.state) : '连接中'}</span></button></header>
      <div className="content"><div className="page-heading"><div><p className="eyebrow">{date.replaceAll('-', '.')} · CNY</p><h1>{title}</h1></div><div className="heading-actions"><IconButton title="刷新数据" onClick={() => { void refresh(); }}><RefreshCw size={18}/></IconButton>{['overview','entries','reports'].includes(view) && <button className="button primary" onClick={() => setForm({})}><Plus size={17}/>记一笔</button>}</div></div>
      {error && <div className="alert error"><CircleAlert size={18}/>{error}</div>}
      {status && !status.owner && view !== 'settings' && <div className="setup-banner"><span><Link size={17}/>{status.pendingUser ? '飞书用户等待绑定' : '飞书账户尚未绑定'}</span><button onClick={() => setView('settings')}>前往设置<ChevronRight size={15}/></button></div>}
      {['overview', 'entries'].includes(view) && <div className="filter-bar"><div className="date-range"><CalendarDays size={16}/><input aria-label="开始日期" type="date" value={range.start} onInput={e => { const start = e.currentTarget.value; setRange(r => ({ ...r, start })); }}/><span>至</span><input aria-label="结束日期" type="date" value={range.end} onInput={e => { const end = e.currentTarget.value; setRange(r => ({ ...r, end })); }}/></div><div className="range-shortcuts"><button className="button subtle" onClick={() => setRange({ start: date, end: date })}>今天</button><button className="button subtle" onClick={() => setRange({ start: date.slice(0, 7) + '-01', end: date })}>本月</button></div></div>}
      {loading ? <div className="loading"><LoaderCircle className="spin"/>加载中</div> : view === 'overview' && stats && <>
        <div className="metrics"><div><span>净支出 <ArrowUpRight size={16}/></span><strong>¥{yuan(stats.netExpense)}</strong><small>支出 ¥{yuan(stats.expense)} · 退款 ¥{yuan(stats.refunds)}</small></div><div><span>收入 <ArrowDownLeft size={16}/></span><strong className="green">¥{yuan(stats.income)}</strong><small>{stats.count} 笔记录</small></div><div><span>结余 <Wallet size={16}/></span><strong>¥{yuan(stats.balance)}</strong><small>收入 − 净支出</small></div></div>
        <section className="composer-section"><form className="composer" onSubmit={chat}><span className="composer-mark"><Pencil size={19}/></span><input aria-label="文字记账" placeholder="记一笔…" value={text} onChange={e => setText(e.target.value)} maxLength={4000}/><label className="image-upload-label" title="上传账单或图片"><ImagePlus size={19}/><input aria-label="上传账单或图片" type="file" accept="image/png,image/jpeg,image/webp" disabled={sending} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><button className="send-button" title="发送记账" aria-label="发送记账" disabled={sending || !text.trim()}>{sending ? <LoaderCircle size={18} className="spin"/> : <Send size={18}/>}</button></form>{reply && <div className="chat-reply">{reply}</div>}{chatImages.map(url=><a key={url} href={url} download="账本图表.png"><img className="generated-image" src={url} alt="账本图表"/></a>)}</section>
        <div className="chart-grid"><section><div className="section-heading"><h2>收支走势</h2><div className="legend"><span><i style={{ background: '#167c69' }}/>收入</span><span><i style={{ background: '#d88162' }}/>净支出</span></div></div><div className="bar-chart">{stats.days.length ? stats.days.slice(-14).map(d => { const max = Math.max(100, ...stats.days.slice(-14).flatMap(v => [Math.abs(v.expense), v.income])); return <div className="bar-column" key={d.date}><div className="bars"><div title={`${d.date} 收入 ¥${yuan(d.income)}`} style={{ height: Math.max(d.income ? 3 : 0, d.income / max * 100) + '%' }} className="income-bar"/><div title={`${d.date} 净支出 ¥${yuan(d.expense)}`} style={{ height: Math.max(d.expense ? 3 : 0, Math.abs(d.expense) / max * 100) + '%', opacity: d.expense < 0 ? .45 : 1 }} className="expense-bar"/></div><small>{d.date.slice(5)}</small></div>; }) : <div className="chart-empty">暂无收支数据</div>}</div></section><section><div className="section-heading"><h2>支出分类</h2><span className="muted">{stats.unclassified > 0 ? `${stats.unclassified} 笔待分类` : '按净支出'}</span></div><div className="category-chart">{stats.categories.length ? stats.categories.slice(0, 6).map((c, i) => <div className="category-row" key={c.name}><div><span><i style={{ background: colors[i] }}/>{c.name}</span><strong>¥{yuan(c.amount)}</strong></div><div className="category-track"><span style={{ width: Math.abs(c.amount) / Math.max(1, ...stats.categories.map(c => Math.abs(c.amount))) * 100 + '%', background: colors[i] }}/></div></div>) : <div className="chart-empty">暂无分类数据</div>}</div></section></div>
        <section className="recent-section"><div className="section-heading"><h2>最近记录</h2><button className="text-button" onClick={() => setView('entries')}>全部明细<ChevronRight size={15}/></button></div>{list(entries.slice(0, 6), true)}</section>
      </>}
      {!loading && view === 'entries' && <><div className="entry-filters"><div className="search-input"><Search size={16}/><input aria-label="搜索账目" placeholder="搜索商家、备注、编号" value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="收支类型" value={kind} onChange={e => setKind(e.target.value)}><option value="">全部类型</option>{Object.entries(names).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><select aria-label="分类筛选" value={category} onChange={e => setCategory(e.target.value)}><option value="">全部分类</option>{[...new Set([...categories, ...entries.map(e => e.category)])].map(c => <option key={c}>{c}</option>)}</select><label className="checkbox-label"><input type="checkbox" checked={cancelled} onChange={e => setCancelled(e.target.checked)}/>已撤销</label><a className="button" href={'/api/export?' + new URLSearchParams({ ...range, ...(kind ? { kind } : {}), ...(category ? { category } : {}), ...(query ? { q: query } : {}), includeCancelled: String(cancelled) })}><Download size={16}/>导出</a></div><div className="table-caption">{entries.length} 笔记录</div>{list(entries)}</>}
      {!loading && view === 'reports' && <><div className="report-toolbar"><div className="date-range"><input aria-label="账单开始日期" type="date" value={range.start} onInput={e => { const start = e.currentTarget.value; setRange(r => ({ ...r, start })); }}/><span>至</span><input aria-label="账单结束日期" type="date" value={range.end} onInput={e => { const end = e.currentTarget.value; setRange(r => ({ ...r, end })); }}/></div><button className="button" onClick={async () => { try { setReportText((await api<{ text: string }>('/reports/preview', { ...range, period: 'monthly' })).text); } catch(e) { notify((e as Error).message); } }}><FileText size={16}/>生成账单</button></div><div className="report-list">{reports.map(r => <button key={r.id} className="report-item" onClick={() => setReportText(r.text)}><FileText size={22}/><div><strong>{r.period === 'daily' ? '日' : r.period === 'weekly' ? '周' : '月'}账单</strong><span>{r.start} 至 {r.end}</span></div><small>{r.cutoff}</small><ChevronRight size={17}/></button>)}{reports.length === 0 && <div className="empty"><FileText size={32}/><p>暂无定期账单</p></div>}</div></>}
      {!loading && view === 'activity' && status && <div className="activity-content"><section><h2>连接与任务</h2><div className="health-row"><span><Activity size={18}/>飞书长连接</span><b>{stateName(status.bot.state)}</b></div><div className="health-row"><span><Send size={18}/>待发送消息</span><b>{status.outbox}</b></div><div className="health-row"><span><Database size={18}/>最近备份</span><b>{status.lastBackup || '暂无'}</b></div>{status.bot.lastError && <div className="alert error">{status.bot.lastError}</div>}</section><section><h2>待确认记录 <span className="muted">{status.confirmations.length}</span></h2>{status.confirmations.map(c => <div className="confirmation" key={c.id}><strong>C{c.id} · {c.action.type === 'refund' ? '退款' : c.action.type === 'update' ? '修改' : '撤销'} {c.action.amount ? `¥${c.action.amount}` : ''}</strong>{c.candidates.map(e => <button className="candidate" key={e.id} onClick={async () => { try { const r = await api<{ result: string }>('/confirm', { id: c.id, entry: e.id }); notify(r.result); refresh(); } catch(err) { notify((err as Error).message); } }}><span>#{e.id} · {e.date} · {e.merchant || e.note}</span><strong>¥{yuan(e.amount)}</strong><Check size={16}/></button>)}</div>)}{status.confirmations.length === 0 && <p className="quiet-empty"><CircleCheck size={18}/>暂无待确认记录</p>}</section><section><h2>待处理消息 <span className="muted">{status.pendingMessages.length}</span></h2>{status.pendingMessages.map(m => <div className="pending-message" key={m.id}><div><strong>{m.text}</strong><small>{m.error || '等待处理'} · {new Date(m.received_at).toLocaleString('zh-CN')}</small></div><IconButton title="重试消息" onClick={async () => { try { const r = await api<{ result: string }>('/messages/retry', { id: m.id }); notify(r.result); refresh(); } catch(e) { notify((e as Error).message); } }}><RefreshCw size={16}/></IconButton><IconButton title="忽略消息" onClick={async () => { try { await api('/messages/dismiss', { id: m.id }); refresh(); } catch(e) { notify((e as Error).message); } }}><X size={16}/></IconButton></div>)}{status.pendingMessages.length === 0 && <p className="quiet-empty"><CircleCheck size={18}/>暂无待处理消息</p>}</section></div>}
      {!loading && view === 'accounts' && funds &&
        <AccountsView funds={funds} today={date} request={api} saved={() => { void refresh(); notify('账户已保存'); }}/>
      }
      {!loading&&view==='possessions'&&<PossessionsView items={items} archived={archived} setArchived={setArchived} request={api} saved={()=>{void refresh();notify('物品已保存');}}/>}
      {!loading&&view==='loans'&&loans&&funds&&<LoansView pool={loans} accounts={funds.accounts} today={date} request={api} saved={()=>{void refresh();notify('借款记录已保存');}}/>}
      {!loading&&view==='reports'&&<ChartControls range={range} request={api} notify={notify}/>}
      {!loading && view === 'settings' && status && <SettingsView status={status} refresh={refresh} toast={notify}/>}
      </div><footer className="page-footer"><span>私人账本</span><span>人民币 · Asia/Shanghai</span></footer>
    </main>
    {toast && <div className="toast" role="status">{toast}</div>}
    {form && <EntryForm entry={form.entry} refund={form.refund} today={date} accounts={funds?.accounts || []} close={() => setForm(null)} saved={() => { void refresh(); notify('记录已保存'); }}/>}
    {deleting && <Modal title="撤销记录" close={() => setDeleting(null)}><p>撤销 #{deleting.id} · {deleting.merchant || deleting.note || deleting.category} · ¥{yuan(deleting.amount)}？</p><footer><button className="button" onClick={() => setDeleting(null)}>取消</button><button className="button danger" onClick={remove}><Trash2 size={16}/>撤销</button></footer></Modal>}
    {reportText && <Modal title="账单" close={() => setReportText('')}><pre className="report-text">{reportText}</pre><footer><button className="button" onClick={() => { const url = URL.createObjectURL(new Blob([reportText], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = '账单.txt'; a.click(); URL.revokeObjectURL(url); }}><Download size={16}/>下载</button></footer></Modal>}
    {history && <Modal title="修改历史" close={() => setHistory(null)}><div className="history-list">{history.map((h, i) => <div key={i}><strong>{{ create: '新增', update: '修改', cancel: '撤销' }[h.action] || h.action}</strong><small>{new Date(h.created_at).toLocaleString('zh-CN')}</small>{h.before_json && <pre>修改前：{historyText(h.before_json)}</pre>}{h.after_json && <pre>修改后：{historyText(h.after_json)}</pre>}</div>)}</div></Modal>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
